#server:
#  port: 12000
#
#  redis:
#    host: 192.168.56.10
#    port: 6379
#
##开启feign对sentinel的支持
#feign:
#  sentinel:
#    enabled: true
#
#  thymeleaf:
#    cache: false
#
#  session:
#    store-type: redis
#
#logging:
#  level:
#    com.xunqi.hcqmall.search: debug
#    root: warn
#  pattern:
#    console: "%d{yyyy-MM-dd} [%thread] - %msg%n"
#
##暴露所有端点
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
