spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tRK2jBJBBbLdRtUMdwy
      secret-key: flP8lTAfm54XhXMzR3IR4QYhXkjAhH
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        bucket: gulimall-b666112

      sms:
        host: http://dingxin.market.alicloudapi.com
        path: /dx/sendSms
        appCode: 60585ae5a76445b8badf93f727d36ec1
        tpl_id: TP1711063
  application:
    name: gulimall-third-party
server:
  port: 30000


