spring:
  cloud:
    gateway:
      routes:
        - id: product_route
          uri: lb://hcqmall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: hcqmall_search_route
          uri: lb://hcqmall-search
          predicates:
            - Host=search.hcqmall.com

        - id: coupon_route
          uri: lb://hcqmall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: third_party_route
          uri: lb://hcqmall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

        - id: member_route
          uri: lb://hcqmall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}


        - id: ware_route
          uri: lb://hcqmall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}


        - id: hcqmall_host_route
          uri: lb://hcqmall-product
          predicates:
            - Host=hcqmall.com,item.hcqmall.com

        - id: hcqmall_auth_route
          uri: lb://hcqmall-auth-server
          predicates:
            - Host=auth.hcqmall.com

        - id: hcqmall_cart_route
          uri: lb://hcqmall-cart
          predicates:
            - Host=cart.hcqmall.com

        - id: hcqmall_order_route
          uri: lb://hcqmall-order
          predicates:
            - Host=order.hcqmall.com

        - id: hcqmall_member_route
          uri: lb://hcqmall-member
          predicates:
            - Host=member.hcqmall.com


        - id: hcqmall_seckill_route
          uri: lb://hcqmall-seckill
          predicates:
            - Host=seckill.hcqmall.com
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: test_route
#          uri: https://www.baidu.com
#          predicates:
#            - Query=url,baidu
#
#        - id: qq_route
#          uri: https://www.qq.com
#          predicates:
#            - Query=url,qq

